#!/bin/bash
GIT_DIR="/home/ubuntu/presentation/moringa.git/"
TARGET="/home/ubuntu/presentation/moringa"
DEPLOY_BRANCH="master"
while read oldrev newrev ref    
do
        #checks out the branch we would love to deploy
        if [[ $ref = refs/heads/$DEPLOY_BRANCH ]];
        then
                echo "Deploy branch:$ref received. Deploying deploy branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $DEPLOY_BRANCH
        else
                echo "Ref $ref successfully received. Doing nothing: only the ${DEPLOY_BRANCH} branch may be deployed to production... "
        fi
done

~                                     